### ISSUE TITLE
More sources of data

### ISSUE THREAD

**Issue by blokhin** [hackingmaterials/matminer#13]
Thanks for this project! This is not an issue, but more like a feature request: would you be interested in adding more sources of data (e.g. Nomad, Materials Cloud etc.)?

**Comment by computron** [comment]
Hi Evgeni,

It's great to hear you found this. I would say that this code is likely going to be largely in hibernation for next two months or so. After that, we are going to be working a lot on the descriptors part of the problem.

As for other data sources, we would certainly be very interested in more data sources. The only caveats are:
i) We may not have the development time to do it ourselves
ii) Because we are putting all the data into a pandas data frame with the idea of mixing analysis between different data entries, the data should have some degree of uniformity. For the data sources you mentioned, it's possible that the results will all be from different theoretical techniques because they compile user calculations done according to the preference of the user. So the query tool would need to be more sophisticated than for something like Materials Project (where the parameters are all uniform) to account for the heterogeneity in theory being applied.
