### ISSUE TITLE
why double_underscore variables?

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#166]
e.g. BaseFeaturizer has ``__ignore_errors`` which is double underscore. Why not single underscore ``_ignore_errors``?

**Comment by ardunn** [comment]
@WardLT and I talked about this is #119 I think. Double underscore prepends the class name (in this case the parent class `BaseFeaturizer`) to `__ignore_errors` with "name mangling". 

This would be useful in the case when `._ignore_errors` is some private attribute of a Featurizer, since `_ignore_errors` can be overridden by the child but `_BaseFeaturizer__ignore_errors` cannot. Outside of that use case, there is no reason for not using `_ignore_errors`.

**Comment by computron** [comment]
OK sounds reasonable, thanks!
