### ISSUE TITLE
Branch Point Energy calculation issue

### ISSUE THREAD

**Issue by sam14au** [hackingmaterials/matminer#167]
I’m trying to use matminer to calculate the branch point energy but this requires the uniform band structure. I'm using an API to pull the band structure from Materials Project but from what I can tell, it is only possible to get the band structure at line mode band structure using MPRester. Is there any way to use an API to get the uniform band structure for a list of compounds from MP, allowing me to calculate the BPE for each? Or alternatively, can the code be modified so that BPE works with line mode band structures?

**Comment by computron** [comment]
- It is true that MP doesn't have a way to pull uniform band structures. I have advocated for this for some time, but it is really something that needs to be coordinated with Materials Project and not matminer. I see you have posted an issue to the MP forum, that is the appropriate venue for the request.
- For BPE with line mode, BPE is intended to take an integral over all of k-space. A line-mode band structure doesn't allow one to do this (this is why one also doesn't compute total energies from line mode calculations). Of course if one wanted very coarse results they could "cheat" and use the line mode, and if you had materials with the same k-path any errors might even be systematic and usable, but I don't think it's worth spending effort coding a method that's the incorrect definition.

I will bring up the uniform band structure issue in my next meeting with MP to see if they can push this forward, that is the proper solution to this rather than redefining the branch point energy to not be a proper integral over k-space. Alternatively, you could consider using our *atomate* package (https://hackingmaterials.github.io/atomate/) to compute the uniform band structures yourself.

**Comment by sam14au** [comment]
Thanks, I'll watch the response on that forum as well. Please keep me updated about the status as to whether (and when) this might be implemented.
