### ISSUE TITLE
Tiny bugs in get_pymatgen_descriptor(）?

### ISSUE THREAD

**Issue by ning213** [hackingmaterials/matminer#18]
Hello!
      Thanks for your excellent program. I get some trouble in 'get_pymatgen_descriptor('Com','ionic_radii'). It reports this bug "TypeError: float() argument must be a string or a number, not 'dict'". Maybe you can fix this bug. Thanks!

**Comment by computron** [comment]
Hi @ning213,

Thanks for your report. I personally won't be doing much support of matminer until mid-August or so, which is when I'll take a serious look into the code and make improvements. Hopefully one of the previous developers like @saurabh02 can help out in the meantime.

**Comment by computron** [comment]
@ning213 I looked again and "ionic_radii" is not one of the valid descriptors to choose. Basically, you need to choose one of the descriptors that yields a numerical value for each element - ionic_radii instead returns a dict for an Element.

You can try an alternate descriptor such as:

```
from matminer.descriptors.composition_features import get_pymatgen_descriptor
print(get_pymatgen_descriptor('NaCl','average_ionic_radius'))
```

I pushed a change so that someone trying to use ionic_radii gets a clearer error message that this is not a valid descriptor choice. Also, as I mentioned I'll be getting more involved in matminer at a later point and things should become clearer / better then.
