### ISSUE TITLE
Add the Many-Body Tensor Representation

### ISSUE THREAD

**Issue by WardLT** [hackingmaterials/matminer#241]
Matthias Rupp will be open sourcing source code the [Many-Body Tensor Representation](https://arxiv.org/pdf/1704.06439.pdf). We should build a wrapper to implement the BaseFeaturizer API, either for his package or ours.

@computron - Mathias mentions you have already done this, right?

**Comment by computron** [comment]
@kylebystrom was working on this; I believe he already had something in place, but he should probably give the update.

I would suggest to have the Python featurizer interface in matminer itself (the one that extends BaseFeaturizer), this will keep all the featurizers in one place. The featurizer can have a dependency if needed to some other code (e.g., qmmlpack, etc.) that might need to be compiled, etc. in order to use it. When talking to Mattias and Haoyan, they expressed concern over speed of the MBTR in pure Python and preferred the underlying implementation to be C++.

**Comment by ardunn** [comment]
Hey @kylebystrom, did you ever wind up implementing this? Or if not, have some starter code etc.?

**Comment by muu4649** [comment]
Hi! This group makes nice module about MBTR!
https://github.com/SINGROUP/dscribe
But, I don't try it .....
Im happy if it helps you.

**Comment by computron** [comment]
Looks very promising! Matthias Rupp's group was supposed to also release their own Python bindings to MBTR via qmmlpack (see https://gitlab.mpcdf.mpg.de/nomad-lab/public-wiki/wikis/NOMAD-software-and-source-code-release, it may require login)? but I don't see a usable implementation anywhere yet. The SINGROUP dscribe code might be a better bet

**Comment by muu4649** [comment]
Did this information help you?（So Im happy!）
um...qmmlpack's visibility is now private ..
Had Matthias Rupp made his achievement open source license?

**Comment by hhaoyan** [comment]
Hello everyone!

Happy to find this issue and I'm considering finishing what was left behind :)

The current situation is that I had a C++ implementation and I used it to conduct most of the research. In the meantime, Matthias also had a C++ implementation which he included in his package for doing quantum machine learning. 
Both worked and the difference might that Matthia's code is more designed and faster (both faster than Python codes, which I used a long time ago)...

I have ported my implementation here (https://github.com/hhaoyan/mbtr), I'm also thinking to contact Matthias if he is happy to open-source his code.

**Comment by lauri-codes** [comment]
Hi all,

Since matminer is already using at least the SOAP-descriptor from the DScribe package, I would suggest using the DScribe implementation of MBTR. Similar to the SOAP implementation it has a clear and comprehensive python API which is backed by a very fast C++ extension.

If you want to go this way, I can also help in building the featurizer. Should be largely a copy-paste of the SOAP-featurizer.

**Comment by computron** [comment]
Sounds like a great plan to me!

Let us know if you run into any issues.

**Comment by computron** [comment]
@ardunn can you get in touch with @lauri-codes to see what the best way forward would be?

**Comment by ardunn** [comment]
@lauri-codes sounds like a great idea. Maybe we can just include this with a PR for the soap featurizer, once we have that figured out

**Comment by ardunn** [comment]
superseded by #635
