### ISSUE TITLE
make the DOS featurizers more "smooth" and less "hard"

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#246]
See discussion on:

https://github.com/hackingmaterials/matminer/issues/240#issuecomment-395229082

**Comment by dyllamt** [comment]
I would like to work on this. I can think of two ways that this can be accomplished, but would like others opinions on the two methods.

1. The first method applies to both `DOSFeaturizer` and `BandEdge`. In both, the partial DOS is weighted by an exponentially decaying function. For `BandEdge`, the decay constant will depend on the DOS mass, while the decay constant will be the same for all compounds in `DOSFeaturizer`.
2. The second method would add another dimension to the features generated. In this method you track the contributions to the partial DOS in sub-energy windows. This is an "energy distribution function", analogous to a radial distribution function, but for density of states. You'll still have a hard cutoff where your last bin is, but it's "smoother" since you track the change in DOS composition with energy.

Maybe its best to implement option 2 in `DOSFeaturizer` and option 1 in `BandEdge`?

**Comment by albalu** [comment]
I like the idea of using DOS mass for decay constant by default. I am having a hard time imagining how option 2 works, so we will have more features like cbm_s_0.0-0.05, cbm_s_0.05-0.10 , etc; i.e. contribution in energy windows? Option 1 is simpler.

**Comment by dyllamt** [comment]
Option 2 adds some level of spectral information to the features, but for now, I'll go ahead and implement option 1 along with an entropy-type score in the `DOSFeaturizer`. If we like it, it will be easy to extend these changes to `BandEdge`.

**Comment by computron** [comment]
The "spectral" type approach has been somewhat explored before, see for example:

Isayev, O. et al. Materials Cartography: Representing and Mining Material Space Using Structural and Electronic Fingerprints. Chem. Mater. 141215151057004 (2014). doi:10.1021/cm503507h

It's probably somewhat useful for describing a distance metric between DOSes and might be useful in kernel methods. But I think it would take a little fiddling to make it useful. The first method of a single number is probably good enough to start with

**Comment by ardunn** [comment]
Old issue, was closed by #246
