### ISSUE TITLE
MultipleFeaturizer with mixed dtypes

### ISSUE THREAD

**Issue by albalu** [hackingmaterials/matminer#289]
When output data is mixture of numbers and str (pandas object) MultipleFeaturizer converts all of them to object which is pretty bad. For example, the following test under "test_composition.py" would fail.

```
def test_multifeat_dtypes(self):
    featzers = [
        Stoichiometry(),
        AtomicOrbitals()
    ]
    multifeat = MultipleFeaturizer(featzers)
    df = multifeat.featurize_dataframe(self.df, col_id='composition')
    self.assertEqual(set(df.dtypes.astype(str)), {'float64', 'int64', 'object'})
```

if I override get_dataframe inside MultipleFeaturizer, the problem is fixed (also the progress bars work for each featurizer as opposed to only for MultipleFeaturizer). However, it seems like it fails some caching tests. @WardLT , this seems to be related to your code? Unfortunately, at the moment, I don't have a solution to both these issues:

```
def featurize_dataframe(self, df, col_id, **kwargs):
    multiindex = kwargs.get("multiindex", False)
    for i, featzer in enumerate(self.featurizers):
        if i>0 and multiindex:
            col_id = ('Input Data', col_id)
            multiindex = False
        df = featzer.featurize_dataframe(df, col_id, **kwargs)
    return df
```

**Comment by ardunn** [comment]
@albalu if you revert to before the caching commit was made on multifeaturizer, does it solve the issue? if so we will at least know where to start on fixing

**Comment by albalu** [comment]
Yes, revering fixes it. Same as if we define MultipleFeaturizer.featurize_dataframe as my example above. In both cases, it seems to skip caching. I remember you guys had similar issues with MultipleFeaturizer before. I couldn't find an easy fix for it.

**Comment by WardLT** [comment]
Thanks for finding this error and the nice unit test @albalu! 

As you've probably seen, I've got a tentative solution to this issue in #290. One problem is that I use numpy.hstack, which [changes numbers to strings when you have mixed dtypes](https://stackoverflow.com/questions/39754658/concatenate-arrays-with-mixed-types). 

I'm working to remove hstack (which was nice, because it is robust to whether I use ndarrays or lists), but it is breaking other things.

This change will keep the caching functionality, but still won't make the multiple progress bars for different featurizers.

**Comment by WardLT** [comment]
Well, my initial approach about removing `hstack` was not a good one. I've got it working now by creating arrays of numpy `dtype=object` before concatenating features, which prevents numpy from recasting numbers as strings.

I've also confirmed that this fixes the unit test you provided, though I used a generic one when implementing the fix.
