### ISSUE TITLE
Change the way examples are handled to an sklearn-esque "download if needed" model

### ISSUE THREAD

**Issue by Doppe1g4nger** [hackingmaterials/matminer#292]
Something that struck me when looking at the matminer examples is that the example data is installed alongside the code by default. To put the impact of that into perspective: for my local install of matminer the whole package is 27.5MB, of that 26.5MB is from the four csv files that make up the example data.

For comparison sklearn is 18.4MB total and has both larger and more numerous example datasets available than matminer. To achieve this, for any dataset with a more than trivial amount of data sklearn does not install it with the package. Instead when a user first tries to load that dataset a check is made to see if it exists on disk, if not the dataset is downloaded from an external source and is stored in a special sklearn datasets folder. ([See here for an example](http://www.scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html#sklearn.datasets.fetch_california_housing))

If we were to implement a similar system for handling examples in matminer it would: 

1. Reduce the package install overhead, particularly for users who already are familiar with the package and don't need the examples.
2. Allow for more example datasets to be added in the future without increasing the size of the install.
3. Provide a framework for adding very large datasets in the future, if we ever want to add an example for something that required data on the order of hundreds or thousands of MB, such as a deep learning example.

My initial thought is to move the csv files over to the matminer_examples repo and modify the dataframe_loader file to provide the same functionality it has now but with the behavior described above (And also a new file or two would need to be written to handle the downloads elegantly). It would either then save the datasets to a matminer_data folder on the home directory like sklearn does or save them to the library install location in a similar manner to how they are stored currently.

Thoughts?

**Comment by computron** [comment]
My thoughts are:

* I'm not super concerned with the current 27.5MB download size, *but*
* I do think it would be nice to have a better framework for collecting standard data sets, including larger data sets

Some of the other issues on matminer for example pertain to the Jarvis data set which would be nice to have as a standard data set, without increasing the download size of matminer. Even the elastic tensor data set in matminer should have an updated version available since the number of points in MP is now >6000 rather than the ~1000 in the example.

So having a framework for getting additional data sets without having it bloat matminer itself would be very useful. Some comments:

(i) Whatever the framework is, it should be easy to use and seamless. Ideally without a lot of installation quirks and headaches. Scientists are typically bad at installing things and have little patience when things break.
(ii) Probably I'd want to leave the current data sets in there rather than migrate them for the time being, at least until it's really proven that people can use an alternate data set downloader without issues. So the framework would be more for additional data sets.
(iii) Maintaining the framework for hosting data should not be complicated or break-able

Incidentally, we previously played with git-lfs for hosting data and examples. It broke rules 1 and 3 though.
