### ISSUE TITLE
Reference for O'keeffe parameters?

### ISSUE THREAD

**Issue by CJBartel** [hackingmaterials/matminer#32]
Hi I'm hoping you can provide a reference for matminer/matminer/featurizers/data_files/okeeffe_params.json?

I presume these come from https://doi.org/10.1107/S0108768190011041 or some extension but it's not clear which values are pulled (e.g., oxidation state, bonding partner, etc.) or the significance of "r" vs "c".

Thanks,
Chris

**Comment by computron** [comment]
Hi Chris

I actually have no idea why this file is even in matminer. It's already there in pymatgen (the paper there is listed as 'Atoms Sizes and Bond Lengths in Molecules and Crystals'  (O'Keeffe & Brese, 1991)). Unfortunately the file history doesn't reveal who put the file there (since I refactored some file locations in matminer, history seems to be destroyed).

I'm just going to remove the file. Anyone that needs these parameters in matminer should get them from pymatgen.
