### ISSUE TITLE
oxidation states of elements in Composition descriptors

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#37]
@JFChen3 @WardLT Many of the descriptors in composition seem to need knowledge of the oxidation state of an element. As far as I can tell, this is read off some kind of table. But many elements are ambivalent (e.g., P3- in AlP vs P5+ in LiFePO4).

I would suggest using pymatgen Composition's oxi_state_guesses function which I recently developed to guess the oxidation state instead. This should correctly figure out whether P is -, +, or neutral (e.g. P element).

Let me know if you have any issues with the function. If it is slow for large systems let me know because I think I have ideas to speed it up (have an option to reduce the Composition first)

**Comment by computron** [comment]
I can also implement if you want, won't take me long (maybe 3 mins)

Also do you know if the electronegativity tables in Deml are different than those already built in to pymatgen (the latter uses Pauling definition)? If not I might also switch to using pymatgen electronegativity since that doesn't need to be separately loaded. If it's different (e.g. Mulliken) we can keep it the way it is

**Comment by WardLT** [comment]
Sorry for the delayed reply.

If it will not take you long, feel free to make the changes.

The Deml electronegativity tables are also Pauling electronegativities. And
so, I'm also in favor of using the pymatgen version.

On Sep 1, 2017 6:31 PM, "Anubhav Jain" <notifications@github.com> wrote:

I can also implement if you want, won't take me long (maybe 3 mins)

Also do you know if the electronegativity tables in Deml are different than
those already built in to pymatgen (the latter uses Pauling definition)? If
not I might also switch to using pymatgen electronegativity since that
doesn't need to be separately loaded. If it's different (e.g. Mulliken) we
can keep it the way it is

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hackingmaterials/matminer/issues/37#issuecomment-326704289>,
or mute the thread

**Comment by computron** [comment]
ok great, closed via 87c4f029484181f052bb6b1bac1e8bc67cc846fe
