### ISSUE TITLE
Consider moving pymongo and plotly to optional requirements

### ISSUE THREAD

**Issue by afonari** [hackingmaterials/matminer#438]
Hi All,

Can pymongo and plotly be moved to optional requirements. It seems that matminer core functionality shouldn't require these packages.

What do you think?

Related to: https://github.com/hackingmaterials/matminer/issues/16

**Comment by computron** [comment]
I think it's a reasonable suggestion, but could you clarify what the specific problem is?

We need to weigh the problems caused by having the packages be required versus problems caused by removing the packages (people don't have everything working out of the box). So it would be helpful to know what problems are being caused by the packages.

**Comment by afonari** [comment]
There are couple of general considerations:
1. Security - less dependencies - less possibility of a package being hijacked: example: https://www.zdnet.com/article/twelve-malicious-python-libraries-found-and-removed-from-pypi/

2. Updating burden - less dependencies easier to update

3. Packages that are not directly related to the core functionality and also (partially) duplicates other packages. For example matminer requires pymatgen that requires matplotlib. One could argue that plotly and matplotlib can overlap a lot.

pymongo is an entire database (if I understand correctly), of course it is not postgre or mysql, but still it is not clear why matminer would require it (not optional).

**Comment by computron** [comment]
Note - pymongo is just a Python library for connecting to external Mongo databases, it's not a database implementation. Thus, I don't think this is as heavyweight or burdensome as you might think. I haven't heard of any installation issues with it, so I'd favor keeping this unless there is a clear reason to remove.

Plotly could potentially be optional, and I even suggested this be optional in the past (in the issue you referenced). This one is a bit more heavyweight in my opinion and also only used for the "figrecipes" package, which I was always on the fence about us maintaining anyway. I disagree with your reasoning though - plotly provides much more functionality than matplotlib for interactive plots and while both are plotting packages, they are not really the same. Anyway, you could use your same reasoning to argue that pymatgen shouldn't require matplotlib since it's not part of the core functionality, and matplotlib can also have installation issues. I guess pymatgen also took the stance to have "batteries included" and just have things mainly work out of the box rather than requiring further installation to get certain features to work.

Note that I'm not worried about hijacking of either of those libraries. Anyway, the issue is whether to keep the libraries in setup.py / requirements.txt for auto-install - meaning we are not going to have spelling mistakes. There is actually more risk to a user if they need to install the package manually, in which case they might end up typing "pip install plotlee" where "plotlee" is a hypothetical hijacked package.

For now I'm just going to keep things as is.
