### ISSUE TITLE
Type stubs

### ISSUE THREAD

**Issue by janosh** [hackingmaterials/matminer#503]
What's your take on shipping [type stubs](https://mypy.readthedocs.io/en/stable/stubs.html)? This would help modern code analysis tools such as [Pylance](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/) do a better job and as a result make it easier for end users to work with `matminer`.

Specifically, it would prevent issues such as [this one](https://github.com/microsoft/pylance-release/issues/149).

Irrespective of type stubs, it's probably a good idea to address the problem @erictraut described in [pylance-release#149](https://github.com/microsoft/pylance-release/issues/149#issuecomment-661913283)

> the `ConversionFeaturizer.featurize_dataframe` method is calling a method by the same name in its super class, `BaseFeaturizer`. That method, in turn, is calling `_generate_column_labels`, which is calling method `feature_labels`. This method is implemented with a `raise NotImplementedError()` statement, which will throw an exception. It appears that the `BaseFeaturizer` class is intended to be an abstract base class, and `feature_labels` is intended to be an abstract method that is overridden by subclasses. However, `BaseFeaturizer` is not marked as an ABC, nor is `feature_labels` decorated with `@abstractmethod`.

Happy to submit a PR for this if maintainers are busy.

**Comment by ardunn** [comment]
Hey @janosh great idea!

BaseFeaturizer should indeed be ABC. Not sure why it never was. 

I'm also a fan of inline type-hinting (much of which matminer is missing, just because no one has gone through and done it). I'm not fully convinced about stub files though, from a maintainability perspective... mainly mismatching outputs between featurizers in .py files and their stubs in .pyi. 

And yes, PRs welcome!! Please link to  issue if you open it.

**Comment by WardLT** [comment]
Yea, using ABC would be excellent! I second @ardunn and would be happy to help review a PR!

**Comment by janosh** [comment]
Thanks for your offers to review.

@ardunn To be honest, I also prefer inline type hints.

**Comment by computron** [comment]
I see this is closed already, but just wanted to mention that:

- yes, the abc decorators should have already been there, thanks for catching this and offering to add them!
- as discussed by others, I prefer inline versus type stub files, as the former is easier to keep synced and maintain. We've dropped Py2 support since the underlying libraries of matminer (e.g., pymatgen) no longer support Py2 anyway.

**Comment by janosh** [comment]
Oops, closing must have happened by mistake.
