### ISSUE TITLE
normalization for standard deviation in PropertyStats

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#61]
There are two different (common) definitions of standard deviation. One of them has the number of samples in the denominator, n, and the other one has one less (n-1), which is known as Bessel's correction.

The questions are:
- which definition should be used by default
- should we support both as an option

My vote is in favor of n-1 by default. I expect most of the time we will not have a full population in matminer. I expect most matminer users will be trying to build models for the purposes of applying that model on unseen data that is not in the data set, which would go along with the n-1 definition. But this should be discussed to make sure we get the right solution.

**Comment by WardLT** [comment]
@computron, perhaps a first issue to address is "what is our intended use for the `PropertyStats.std_dev` function?" 

There seem to be two possible cases for employing property stats. A first one is measuring the variance in some property across a dataset. In that case, I agree that using the Bessel correction is appropriate because we are estimating the variance with only a sample of all possible entries. 

The other case is using the function is more like measuring the variance as it relates to a certain entry in the dataset. For example, this could be the variance a property across the elements present in the material or across all sites in a crystal. In those cases, we are measuring the variance across the entire population (e.g., all sites in a crystal) and the uncorrected measurement seems more appropriate.

Given that the only current use of PropertyStats in matminer is for the the latter case, I vote we keep using the uncorrected standard deviation by default. I think we should support both as an option, as that we help ensure users of the PropertyStats functions consider which is most appropriate for their application. 

Sound reasonable?

**Comment by computron** [comment]
@WardLT Ok agreed. I was getting std_dev statistics across rows confused with std_dev stats within a row. The option for n-1 probably isn't needed at the moment.
