### ISSUE TITLE
Implement atomic orbital code as features

### ISSUE THREAD

**Issue by computron** [hackingmaterials/matminer#88]
@albalu @dyllamt 

Can you implement the atomic orbital code as a Composition featurizer that gives the pertinent info? I think it's called MolecularOrbitals in pymatgen although I am not sure they are really molecular orbitals

**Comment by dyllamt** [comment]
Hi @computron 

I am currently working on this and have decided that there are two ways this could be implemented. Option one is that the featurizer returns a specified number of the highest energy orbitals contributed by each element. Alternatively, the featurizer could return the highest occupied atomic orbital (by the valence electron count) and lowest unoccupied atomic orbital in the entire composition and then a specified number on either side.

In one case the featurizer will focus on the individual elements, while the later will focus on understanding the orbitals in the entire composition. Any preference? Otherwise I can do both.

**Comment by computron** [comment]
I wiuld be most interested in
- atomic orbital band gap
- absolute energy of HOMO
- absolute energy if LUMO
- character of HOMO
- character of LUMO

Anything else would be up to you, but hopefully we can get those things

**Comment by computron** [comment]
(this was completed)
