### ISSUE TITLE
Error in import composition

### ISSUE THREAD

**Issue by Pangcheng520** [hackingmaterials/matminer#919]
I got an error while typing the following codes:

from matminer.featurizers.base import MultipleFeaturizer
from matminer.featurizers.import composition as cf

The error reported is: ValueError: Unexpected atomic number Z=119

Was it some kind of operator error on my part? Or is there an error in matminer?
[Error in import composition.docx](https://github.com/hackingmaterials/matminer/files/14075019/Error.in.import.composition.docx)

**Comment by ml-evs** [comment]
Yeah, unfortunately there is no-one really keeping matminer up to date with its various dependencies anymore (see also #910, #915, #918) -- I tried a bit last year but hit some roadblocks in #912.

However, the pinned dependencies in the various [`./requirements/*.txt`](https://github.com/hackingmaterials/matminer/tree/main/requirements) have been tested in the CI and should work for a specific version. e.g., if you are using matminer 0.9.0, you can go to the state of the repository at that tag (https://github.com/hackingmaterials/matminer/tree/v0.9.0), download the requirements file and then install matminer as `pip install -r <path to relevant requirements.txt>; pip install matminer` and it should use the tested versions.

Quite a few people are running into this so any volunteers to help out would be great!

**Comment by JaGeo** [comment]
Tagging @naik-aakash and @kaueltzen as they use matminer still quite a lot.

**Comment by ml-evs** [comment]
Hi @JaGeo, I do have maintainer rights here so can merge PRs and make releases, I just don't have any real bandwidth to finish off the fixes related to #912 and the upgrade of pandas. We are still using matminer a little bit too but this is not a dealbreaker for us. I'm happy to review PRs and make releases (and can be very proactive on this) but do not want to commit my time to making fixes forever; I think perhaps this repo should be much more aggressively pinned going forwards, and then people that want to use the latest pymatgen/pandas versions with it will have to contribute it themselves.

So, for now, I think this issue is closed by your PR at #920 but this cannot come into effect until the next matminer release, which is currently blocked by pandas 2 support that breaks certain featurizers (the best approach here may just be to deprecate the featurizers that are failing and skip their tests, if no-one can fix it -- there has never been a guarantee that matminer featurizers don't change value between versions anyway but currently the failures produce all NaNs, e.g., the RDF featurizer).

**Comment by ml-evs** [comment]
For ongoing discussion of how to deal with this: https://github.com/hackingmaterials/matminer/issues/915#issuecomment-1930465088
